[package]
name = "FinSc-Fields-Wiki"
version = "0.1.0"
ipkg = "FinSc-Fields-Wiki.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Transform]
type = "local"
path = "../FinSc-Multiset-Transform"
ipkg = "FinSc-Multiset-Transform.ipkg"

[custom.all.FinSc-Electromagnetism]
type = "local"
path = "../FinSc-Electromagnetism"
ipkg = "FinSc-Electromagnetism.ipkg"

[custom.all.FinSc-Fields]
type = "local"
path = "../FinSc-Fields"
ipkg = "FinSc-Fields.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "../idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"
